function drawMario() {
    draw.fillStyle = "#A33D2E";
    draw.fillRect(7 * unit, 1 * unit, 5 * unit, 1 * unit)
    draw.fillRect(6 * unit, 2 * unit, 9 * unit, 1 * unit)
    draw.fillRect(8 * unit, 8 * unit, 1 * unit, 3 * unit)
    draw.fillRect(9 * unit, 10 * unit, 4 * unit, 1 * unit)
    draw.fillRect(12 * unit, 9 * unit, 1 * unit, 1 * unit)
    draw.fillRect(7 * unit, 11 * unit, 1 * unit, 4 * unit)
    draw.fillRect(6 * unit, 13 * unit, 1 * unit, 2 * unit)
    draw.fillRect(8 * unit, 12 * unit, 1 * unit, 3 * unit)
    draw.fillRect(10 * unit, 10 * unit, 5 * unit, 1 * unit)
    draw.fillRect(11 * unit, 11 * unit, 1 * unit, 3 * unit)
    draw.fillRect(10 * unit, 11 * unit, 1 * unit, 3 * unit)
    draw.fillRect(9 * unit, 11 * unit, 1 * unit, 3 * unit)
    draw.fillRect(12 * unit, 12 * unit, 1 * unit, 3 * unit)
    draw.fillRect(13 * unit, 12 * unit, 1 * unit, 3 * unit)
    draw.fillRect(14 * unit, 14 * unit, 1 * unit, 1 * unit)
    draw.fillRect(12 * unit, 15 * unit, 3 * unit, 1 * unit)
    draw.fillRect(6 * unit, 15 * unit, 3 * unit, 1 * unit)
    draw.fillStyle = "#6A6B20";
    draw.fillRect(6 * unit, 3 * unit, 3 * unit, 1 * unit)
    draw.fillRect(7 * unit, 3 * unit, 1 * unit, 3 * unit)
    draw.fillRect(8 * unit, 5 * unit, 1 * unit, 1 * unit)
    draw.fillRect(5 * unit, 4 * unit, 1 * unit, 3 * unit)
    draw.fillRect(6 * unit, 6 * unit, 1 * unit, 1 * unit)
    draw.fillRect(11 * unit, 3 * unit, 1 * unit, 2 * unit)
    draw.fillRect(12 * unit, 5 * unit, 1 * unit, 1 * unit)
    draw.fillRect(11 * unit, 6 * unit, 4 * unit, 1 * unit)
    draw.fillRect(7 * unit, 8 * unit, 1 * unit, 3 * unit)
    draw.fillRect(6 * unit, 8 * unit, 1 * unit, 4 * unit)
    draw.fillRect(5 * unit, 9 * unit, 1 * unit, 2 * unit)
    draw.fillRect(9 * unit, 8 * unit, 1 * unit, 2 * unit)
    draw.fillRect(10 * unit, 8 * unit, 1 * unit, 2 * unit)
    draw.fillRect(11 * unit, 8 * unit, 1 * unit, 2 * unit)
    draw.fillRect(12 * unit, 8 * unit, 1 * unit, 1 * unit)
    draw.fillRect(13 * unit, 9 * unit, 3 * unit, 1 * unit)
    draw.fillRect(13 * unit, 10 * unit, 3 * unit, 1 * unit)
    draw.fillRect(13 * unit, 11 * unit, 4 * unit, 1 * unit)
    draw.fillRect(14 * unit, 12 * unit, 1 * unit, 1 * unit)
    draw.fillRect(4 * unit, 10 * unit, 1 * unit, 1 * unit)
    draw.fillRect(13 * unit, 16 * unit, 3 * unit, 1 * unit)
    draw.fillRect(13 * unit, 17 * unit, 4 * unit, 1 * unit)
    draw.fillRect(5 * unit, 16 * unit, 3 * unit, 1 * unit)
    draw.fillRect(4 * unit, 17 * unit, 4 * unit, 1 * unit)
  
  
    draw.fillStyle = "#D9A042";
    draw.fillRect(10 * unit, 3 * unit, 1 * unit, 5 * unit)
    draw.fillRect(9 * unit, 3 * unit, 1 * unit, 5 * unit)
    draw.fillRect(6 * unit, 4 * unit, 1 * unit, 2 * unit)
    draw.fillRect(8 * unit, 4 * unit, 1 * unit, 1 * unit)
    draw.fillRect(11 * unit, 5 * unit, 1 * unit, 1 * unit)
    draw.fillRect(12 * unit, 3 * unit, 1 * unit, 2 * unit)
    draw.fillRect(13 * unit, 4 * unit, 2 * unit, 1 * unit)
    draw.fillRect(13 * unit, 5 * unit, 3 * unit, 1 * unit)
    draw.fillRect(7 * unit, 7 * unit, 7 * unit, 1 * unit)
    draw.fillRect(15 * unit, 12 * unit, 2 * unit, 1 * unit)
    draw.fillRect(14 * unit, 13 * unit, 3 * unit, 1 * unit)
    draw.fillRect(15 * unit, 14 * unit, 2 * unit, 1 * unit)
    draw.fillRect(4 * unit, 11 * unit, 2 * unit, 1 * unit)
    draw.fillRect(4 * unit, 12 * unit, 3 * unit, 1 * unit)
    draw.fillRect(4 * unit, 13 * unit, 2 * unit, 1 * unit)
    draw.fillRect(8 * unit, 11 * unit, 1 * unit, 1 * unit)
    draw.fillRect(12 * unit, 11 * unit, 1 * unit, 1 * unit)
    draw.fillRect(7 * unit, 6 * unit, 2 * unit, 1 * unit)
  
  
  
  
  
  }